name: Deploy to EKS with Terraform

on:
  workflow_dispatch:
  # push:
  #  branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.10.3"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "sa-east-1"

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

  eks:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "sa-east-1"

      - name: Set up kubectl
        run: |
          aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

      - name: Deploy app to EKS
        run: |
          kubectl apply -f k8s/app-deployment.yaml
          kubectl set env deployment/food-deployment DB_HOST=${{ secrets.DB_HOST }} DB_PORT=${{ secrets.DB_PORT }} DB_BASE=${{ secrets.DB_BASE }} DB_USER=${{ secrets.DB_USER }} DB_PASS=${{ secrets.DB_PASS }}
          kubectl apply -f k8s/app-service.yaml

      - name: Monitor Deployment Status
        run: |
          kubectl rollout status deployment/food-deployment
